### PR TITLE
Add Name Label

### PR DESCRIPTION
**Pull request by MitraSafari93**

### CODE REVIEW

**Comment by reza-qadimi** [comment]
Note: Please lock controls to prevents them from being dragged to a new size or location on the design surface!

**Review by reza-qadimi — CHANGES_REQUESTED** [review]
Note:
Please lock controls to prevents them from being dragged to a new size or location on the design surface!

**Comment by MitraSafari93** [comment]
> Note:
> Please lock controls to prevents them from being dragged to a new size or location on the design surface!

**Comment by MitraSafari93** [comment]
All controls are locked in Form04

**Comment by reza-qadimi** [comment]
Well Done!

**Pull request merged**
